name: mcphoto
favicon: null
layout_spectrum: 0.25159
typography_spectrum: 0.19871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.8728274882305413
  lightness: 0.13203380233608186
  saturation: 0.5434776588808745
  rhythmicContrast: 0.8417080328799784
purpose: []
